# Bluesky-based control development for 2020-2 run 

Test the OOP-based experiment control for
* Tomography
* Near field
* Far field

## Preparation

In [1]:
import numpy as np
import matplotlib
import bluesky
import ophyd
import apstools
import databroker
from datetime import datetime

In [2]:
scan_cfg = 'seisidd/config/scan_template.yml'

## Tomography

In [3]:
# instantiate the experiment handle
from seisidd.experiment import Tomography

testTomo = Tomography(mode='dryrun')

In [4]:
# summarize plan
testTomo.dryrun(scan_cfg)

att__motor -> 1
foil__motor -> 1
Tomo configuration:
energyfoil = 1 
attenuation = EpicsMotorTuple(user_readback=1.008, user_setpoint=1.0, user_offset=0.0, user_offset_dir=0, offset_freeze_switch=0, set_use_switch=0, velocity=2.1, acceleration=1.0, motor_egu='pos', motor_is_moving=0, motor_done_move=1, high_limit_switch=0, low_limit_switch=0, high_limit_travel=24.5, low_limit_travel=0.5, direction_of_travel=1, motor_stop=0, home_forward=0, home_reverse=0) 
type = step 
n_white = 5 
n_dark = 5 
sample_out_position:
  kx = -1 
  kz = 0 
acquire_time = 0.5 
acquire_period = 0.51 
omega_step = 0.5 
omega_start = 0.0 
omega_end = 20.0 
n_frames = 5 
ROT_STAGE_FAST_SPEED = 1 
accl = 3 
readout_time = 0.001 
n_projections = 41 
total_images = 56 
focus_beam = False 
initial_kx = -2.0 
initial_kz = 0.0 
fronte_white_kx = -3.0 
fronte_white_kz = 0.0 
back_white_kx = -2.9396926207859084 
back_white_kz = 0.3420201433256687 

Output:
filepath = /home/beams/S6HEDM/data/ssd/test_pre2020-2 
fileprefi

In [5]:
testTomo.check(scan_cfg)

Tomo configuration:
energyfoil = 1 
attenuation = 1 
type = step 
n_white = 5 
n_dark = 5 
sample_out_position:
  kx = -1 
  kz = 0 
acquire_time = 0.5 
acquire_period = 0.51 
omega_step = 0.5 
omega_start = 0.0 
omega_end = 20.0 
n_frames = 5 
ROT_STAGE_FAST_SPEED = 1 
accl = 3 
readout_time = 0.001 

Output:
filepath = /home/beams/S6HEDM/data/ssd/test_pre2020-2 
fileprefix = test2020_2 
type = tiff 



In [6]:
testTomo.run(scan_cfg)

Tomo configuration:
energyfoil = 1 
attenuation = EpicsMotorTuple(user_readback=1.008, user_setpoint=1.0, user_offset=0.0, user_offset_dir=0, offset_freeze_switch=0, set_use_switch=0, velocity=2.1, acceleration=1.0, motor_egu='pos', motor_is_moving=0, motor_done_move=1, high_limit_switch=0, low_limit_switch=0, high_limit_travel=24.5, low_limit_travel=0.5, direction_of_travel=1, motor_stop=0, home_forward=0, home_reverse=0) 
type = step 
n_white = 5 
n_dark = 5 
sample_out_position:
  kx = -1 
  kz = 0 
acquire_time = 0.5 
acquire_period = 0.51 
omega_step = 0.5 
omega_start = 0.0 
omega_end = 20.0 
n_frames = 5 
ROT_STAGE_FAST_SPEED = 1 
accl = 3 
readout_time = 0.001 
n_projections = 41 
total_images = 56 
focus_beam = False 
initial_kx = -2.0 
initial_kz = 0.0 
fronte_white_kx = -3.0 
fronte_white_kz = 0.0 
back_white_kx = -2.9396926207859084 
back_white_kz = 0.3420201433256687 

Output:
filepath = /home/beams/S6HEDM/data/ssd/test_pre2020-2 
fileprefix = test2020_2 
type = tiff 



T

('139bbb91-6111-4ada-8405-1312cf59ff2c',)

## Near-field

In [6]:
# instantiate the experiment handle
from seisidd.experiment import NearField

testNF = NearField(mode='dryrun')

In [7]:
testNF.dryrun(scan_cfg)

NearField configuration:
energyfoil = 1 
attenuation = 1 
type = fly 
sample_out_position:
  kx = -1 
  kz = 0 
detector_z_position:
  nf_z1 = 7 
  nf_z2 = 10 
volume:
  ky_start = 2.5 
  ky_step = 0.5 
  n_layers = 10 
acquire_time = 0.1 
omega_step = 0.2 
omega_start = 0.0 
omega_end = 360.0 
n_frames = 1 
ROT_STAGE_FAST_SPEED = 1 
accl = 3 
readout_time = 0.001 
n_projections = 1801 
total_images = 1801 
focus_beam = False 
slew_speed = 1.9790985206238558 
initial_kx = 0.0 
initial_kz = 0.0 
fronte_white_kx = -1.0 
fronte_white_kz = 0.0 
back_white_kx = -1.0 
back_white_kz = 0.0 

Output:
filepath = /data 
fileprefix = test 
type = tif 

nfstage_ky -> 2.5
=================================== Open Run ===================================
det_tiff1_file_path -> /data
det_tiff1_file_name -> test_layer000001
det_tiff1_file_write_mode -> 2
det_tiff1_num_capture -> 3602
det_tiff1_file_template -> %s%s_%06d.tif
det_hdf1_file_path -> /data
det_hdf1_file_name -> test_layer000001
det_hdf1_file_

## Far-field

In [3]:
from seisidd.experiment import FarField

testFF = FarField(mode='dryrun')

In [4]:
testFF.dryrun(scan_cfg)

FarField configuration:
energyfoil = 1 
attenuation = 1 
type = fly 
sample_out_position:
  kx = -1 
  kz = 0 
detector_z_position:
  ff_z1 = 7 
volume:
  ky_start = 2.5 
  ky_step = 0.5 
  n_layers = 10 
n_dark = 5 
acquire_time = 0.1 
acquire_period = 0.11 
omega_step = 0.2 
omega_start = 0.0 
omega_end = 10.0 
n_frames = 1 
ROT_STAGE_FAST_SPEED = 1 
accl = 3 
readout_time = 0.001 
n_projections = 51 
total_images = 61 
focus_beam = False 
slew_speed = 1.9413706076489998 
initial_kx = 0.0 
initial_kz = 0.0 
fronte_white_kx = -1.0 
fronte_white_kz = 0.0 
back_white_kx = -0.984807753012208 
back_white_kz = 0.17364817766693033 

Output:
filepath = /data 
fileprefix = test 
type = tif 

ffstage_ky -> 2.5
=================================== Open Run ===================================
det_tiff1_file_path -> /data
det_tiff1_file_name -> test_layer000001
det_tiff1_file_write_mode -> 2
det_tiff1_num_capture -> 61
det_tiff1_file_template -> %s%s_%06d.tif
det_hdf1_file_path -> /data
det_hdf1_f

In [7]:
from epics import caget, caget_many

In [9]:
caget('S:IOC:timeOfDayForm1SI')

'July 05, 2020 16:00:38'

In [10]:
caget('OPS:message3')

'0+24x1 RHB, 120 second Top-up'

In [11]:
pvs = [
"1idPG4:cam1:Manufacturer_RBV",   
"1idPG4:cam1:Model_RBV",          
"1idPG4:cam1:SerialNumber_RBV",   
"1idPG4:cam1:FirmwareVersion_RBV",
"1idPG4:cam1:SDKVersion_RBV",     
"1idPG4:cam1:DriverVersion_RBV",  
"1idPG4:cam1:ADCoreVersion_RBV",  
"1idPG4:cam1:AcquireTime",        
"1idPG4:cam1:AcquirePeriod",      
"1idPG4:cam1:FrameRateValAbs",    
"1idPG4:cam1:FrameRateOnOff_RBV", 
"1idPG4:cam1:Gain",               
"1idPG4:cam1:DataType_RBV",       
"1idPG4:cam1:ArrayCounter_RBV",   
"1idPG4:cam1:TemperatureActual",  
"1idPG4:cam1:FrameType",          
"1idPG4:HDF1:FileName",           
"1idPG4:HDF1:FullFileName_RBV",   
"1idPG4:HDF1:FilePath_RBV",       
"1idPG4:HDF1:PluginType_RBV" ,    
"S:IOC:timeOfDayForm1SI",         
"S:IOC:timeOfDayForm1SI" ,        
"S:SRcurrentAI" ,                
"S:TopUpStatus" ,                 
"OPS:message3" , 
"1idPG4:cam1:MaxSizeX_RBV" ,
"1idPG4:cam1:MaxSizeY_RBV" ,
"1idPG4:cam1:MinX"   ,      
"1idPG4:cam1:MinY"    ,     
"1idPG4:cam1:SizeX"    ,    
"1idPG4:cam1:SizeY"     ,   
"1idPG4:cam1:BinX"       ,  
"1idPG4:cam1:BinY"        , 
]

In [12]:
caget_many(pvs)

['Point Grey Research',
 'Grasshopper3 GS3-U3-23S6M',
 '19343560',
 '2.30.3.0',
 '2.9.3',
 '2.9.0',
 '3.9.0',
 0.5,
 0.509917566870161,
 30.0,
 1,
 1.0,
 3,
 2242,
 54.950000000000045,
 3,
 array([116, 101, 115, 116,  50,  48,  50,  48,  95,  50,   0], dtype=uint8),
 array([ 47, 104, 111, 109, 101,  47,  98, 101,  97, 109, 115,  47,  83,
         54,  72,  69,  68,  77,  47, 100,  97, 116,  97,  47, 115, 115,
        100,  47, 116, 101, 115, 116,  95, 112, 114, 101,  50,  48,  50,
         48,  45,  50,  47, 116, 101, 115, 116,  50,  48,  50,  48,  95,
         50,  95,  48,  48,  48,  48,  48,  55,  46, 104, 100, 102,   0],
       dtype=uint8),
 array([ 47, 104, 111, 109, 101,  47,  98, 101,  97, 109, 115,  47,  83,
         54,  72,  69,  68,  77,  47, 100,  97, 116,  97,  47, 115, 115,
        100,  47, 116, 101, 115, 116,  95, 112, 114, 101,  50,  48,  50,
         48,  45,  50,  47,   0], dtype=uint8),
 'NDFileHDF5 ver1.10.1',
 'July 05, 2020 16:12:28',
 'July 05, 2020 16:12:28',


In [ ]:
# expose internal RunEngine
RE = testexp.RE

# setup the Metadata as before
RE.md['beamline_id'] = 'APS 6'
RE.md['versions'] = {}
RE.md['versions']['apstools'] = apstools.__version__
RE.md['versions']['bluesky'] = bluesky.__version__
RE.md['versions']['databroker'] = databroker.__version__
RE.md['versions']['matplotlib'] = matplotlib.__version__
RE.md['versions']['numpy'] = np.__version__
RE.md['versions']['ophyd'] = ophyd.__version__
RE.md['SESSION_STARTED'] = datetime.isoformat(datetime.now(), " ")

In [ ]:
scan_cfg = 'seisidd/config/scan_template.yml'

In [ ]:
# summarize plan
testexp.dryrun(scan_cfg)

In [ ]:
RE(scan_cfg)


In [ ]:
det = testexp.tomo_det

In [ ]:
det.cam.acquire_time.put(5)

In [ ]:
det.cam.acquire_period.put(4)